### ISSUE TITLE
Legend position

### ISSUE THREAD

**Issue by BenoitGoutorbe** [YuLab-SMU/aplot#16]
Hi, 
I was wandering if it was possible to adjust legend position. 
For instance, in the [example](https://yulab-smu.top/pkgdocs/aplot.html#annoHeatmap) from the vignette, i would like to do something like 

```
my.plot = p %>% insert_left(phr, width=.3) %>% 
  insert_right(pp, width=.4)  %>% 
  insert_right(g, width=.4) %>% 
  insert_top(pc, height=.1) %>% 
  insert_top(phc, height=.2)

my.plot + theme(legend.position="bottom")
```

but i can't make it work...
Thanks this great package and for your help !
Ben

**Comment by GuangchuangYu** [comment]
use `print(my.plot) & theme(legend.position='bottom')` as demonstrated in <https://github.com/YuLab-SMU/aplot/issues/6#issuecomment-912634812>.
