### ISSUE TITLE
zero_range error in 0.1.10

### ISSUE THREAD

**Issue by m3hdad** [YuLab-SMU/aplot#24]
I get the following error in 0.1.10 but everything works fine in 0.1.8 version.
downgrading for now!

```
library(ggplot2)
library(aplot)

p <- p4 |> insert_left(p1,width = .5)
```

```
Error in if (zero_range(as.numeric(limits))) { : 
  missing value where TRUE/FALSE needed
In addition: Warning message:
In zero_range(as.numeric(limits)) : NAs introduced by coercion
```

**Comment by GuangchuangYu** [comment]
pls provide a reproducible example.

**Comment by m3hdad** [comment]
Thanks for prompt reply. @GuangchuangYu could you provide a link so I can share my objects.
`p1` and `p4` are rather complex to share a reproducible code.

Thanks,

**Comment by GuangchuangYu** [comment]
pls send to guangchuangyu AT gmail.com

**Comment by m3hdad** [comment]
It's all in your hands!

**Comment by m3hdad** [comment]
thanks for looking into this.
I believe you are using R 4.2.3 and something has changed since 4.2.1.
We can close the issue since it is not related to aplot.
