### ISSUE TITLE
aplot install error

### ISSUE THREAD

**Issue by xuan13hao** [YuLab-SMU/aplot#28]
Hi Yu,

I try to install 'aplot',but I got this error. Could you help me fix it?

> install.packages("aplot")
Installing package into ‘/home/xuan/R/x86_64-pc-linux-gnu-library/4.1’
(as ‘lib’ is unspecified)
trying URL 'https://cloud.r-project.org/src/contrib/aplot_0.1.10.tar.gz'
Content type 'application/x-gzip' length 23158 bytes (22 KB)
==================================================
downloaded 22 KB

* installing *source* package ‘aplot’ ...
** package ‘aplot’ successfully unpacked and MD5 sums checked
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
Error: object ‘ggbreak2ggplot’ is not exported by 'namespace:ggfun'
Execution halted
ERROR: lazy loading failed for package ‘aplot’
* removing ‘/home/xuan/R/x86_64-pc-linux-gnu-library/4.1/aplot’

The downloaded source packages are in
        ‘/tmp/RtmpIfk9mI/downloaded_packages’
Warning message:
In install.packages("aplot") :
  installation of package ‘aplot’ had non-zero exit status
>

**Comment by GuangchuangYu** [comment]
You need to upgrade ggfun.

**Comment by xuan13hao** [comment]
> You need to upgrade ggfun.
Hi Dr. Yu,

Thanks for your explanation. Could you share a link or a code that helps me upgrade ggfun?

**Comment by GuangchuangYu** [comment]
try: `install.packages("ggfun")`
