### ISSUE TITLE
How to control the spacing between each plot

### ISSUE THREAD

**Issue by wqssf102** [YuLab-SMU/aplot#30]
Hi,
How to control the spacing between each plot?

**Comment by GuangchuangYu** [comment]
It does nothing in the spacing. Each plot can adjust the spacing by using `theme()` if it is a ggplot.

**Comment by GuangchuangYu** [comment]
Another solution is to use `ggplotify::as.ggplot(scale = a-number-less-than-1)` for each plot.

**Comment by wqssf102** [comment]
[options(space.between.plots=XXX)](https://github.com/YuLab-SMU/aplot/pull/31), 
perfect.

**Comment by aldendirks** [comment]
I am attempting to decrease the horizontal space between some subplots to 0 but cannot figure out how to do so. The `options` function only works on the spacing of the last plot added, and even then it can increase the spacing but it cannot decrease it to 0. I have made sure to set all the margins of my supbplots to 0.

```
composite_fig <- plot1 %>% 
  insert_left(plot2) %>%
  insert_left(plot3 width = 0.5) %>%
  insert_left(plot4 width = 0.5)
options(space.between.plots=10)
composite_fig
```
