### ISSUE TITLE
labels were covered when applyed insert_left function

### ISSUE THREAD

**Issue by JaneDY** [YuLab-SMU/aplot#5]
Hi，Y叔
I am not good at R programming.
I applyed insert_left function to combine three plots together, but the labels of first plot were covered by the second plot. 
I have no idea how to solve this problem, and it will be appreciate if you could give some advice.

![image](https://user-images.githubusercontent.com/24492170/92463056-e0472400-f1fd-11ea-98f0-e7eda40458fa.png)

**Comment by GuangchuangYu** [comment]
https://yulab-smu.top/treedata-book/faq.html#faq-label-truncated
