### ISSUE TITLE
aplot object and ggplot object can't draw in a graph

### ISSUE THREAD

**Issue by zzzsssyyy1995** [YuLab-SMU/aplot#7]
There is an aplot object which is generated by insert_xxx() and one ggplot object. Now I want to combined the two items, but they can't draw in a graph? what shoud I deal with it?

**Comment by zzzsssyyy1995** [comment]
Y shushu, help me! Thank you!

**Comment by GuangchuangYu** [comment]
`aplot::plot_list` is able to combine `aplot` and `ggplot`.
